"""Public event fields permitted in the readable live reporter."""

PUBLIC_FIELDS = (
    "reason",
    "assessment",
    "intent",
    "mode",
    "action",
    "action_chunk",
    "hypothesis_proposals",
    "hypothesis_updates",
    "task_updates",
    "world_model_updates",
    "tool_requests",
    "result",
    "resource",
    "amount",
    "input_tokens",
    "output_tokens",
    "latency_ms",
    "error_type",
    "message",
    "checkpoint_id",
    "transition",
    "verification",
    "state",
    "level",
    "levels_completed",
    "observation_hash",
    "available_actions",
    "before_hash",
    "after_hash",
    "changed_cells",
    "checked",
    "passed",
    "mismatches",
)
